### ISSUE TITLE
API Spec

### ISSUE THREAD

**Issue by riseshia** [riseshia/gannbaruzoi#8]
- tasks
- done / undone task
- update task
- create
- delete
- log / unlog

**Comment by riseshia** [comment]
Prototype.

- maybe we could merge done/undone, update, log/unlog...?
- Schema will be update later because it's already quite clear

## Get tasks

```js
// Query
query Tasks {
  tasks {
    id
    estimatedSize
    description
    rootFlg
    doneFlg
    logged
  }
}
```

## Update task

```js
// Query
mutation UpdateTask {
  updateTask(input: {id: 29, estimatedSize: 5}) {
    task {
      id
      estimatedSize
      description
      rootFlg
      doneFlg
      logged
    }
  }
}
```

## Create task

```js
// Query
mutation CreateTask {
  createTask(input: {
    estimatedSize: 1, description: "New Todo", rootFlg: true
  }) {
    task {
      id
      estimatedSize
      description
    }
  }
}
```

## Delete task

```js
// Query
mutation DeleteTask {
  deleteTask(input: {id: 42}) {
    id
  }
}
```

## Log/Unlog

```js
// Query
mutation {
  createLog(input: {taskId: 29}) {
    log
  }
}

mutation {
  deleteLog(input: {taskId: 29}) {
    id
  }
}
```

**Comment by riseshia** [comment]
ping @marocchino how do you think?

**Comment by marocchino** [comment]
UpdateTaskStatus can cover with UpdateTask.
Log/Unlog looks unclear to me.

I want to create delete to log like this.

```js
mutation {
  createLog(taskID: 1) {
    _id
    taskID
  },
  createLog(taskID: 1) {
    _id
    taskID
  } 
}
```

**Comment by riseshia** [comment]
Updated with @marocchino 's review

I'll update once more after I create prototype for graphql test

**Comment by riseshia** [comment]
Updated XD

Question about Edge, Permission case:

- if user try to create log which is for another user
- if user try to delete log when its task has no log
- if user try to update task but fail

**Comment by riseshia** [comment]
you could see sample schema for ruby [here](https://github.com/riseshia/graphql_example/blob/master/app/graph/schema.rb)

**Comment by riseshia** [comment]
graphql returns hash contains key, `errors` when fail XD

**Comment by riseshia** [comment]
Done XD
